
skillMetadata:
  sections:
    - name: Grocy
      fields:
        - name: grocy_api_key
          type: text
          label: Grocy API Key
          value: ""
        - name: grocy_url
          type: text
          label: Grocy URL (without port)
          value: ""
        - name: grocy_port
          type: text
          label: Grocy port
          value: ""